server {
    listen 8080;
    server_name _;
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location = /api {
        default_type application/xml;
        if ($arg_t = caps) {
            rewrite ^ /caps.xml last;
        }
        rewrite ^ /search.xml last;
    }

    location /torrents/ {
        root /usr/share/nginx/html;
        default_type application/x-bittorrent;
    }

    location = /caps.xml {
        root /usr/share/nginx/html;
        default_type application/xml;
    }

    location = /search.xml {
        root /usr/share/nginx/html;
        default_type application/xml;
    }
}
